[tool.poetry]
name = "pybot"
version = "0.0.1"
description = "Bot sample"
authors = ["SaitoTsutomu <tsutomu7@hotmail.co.jp>"]

[tool.poetry.scripts]
pybot = "pybot:main"

[tool.poetry.dependencies]
python = "^3.8"
Flask = "^2.3.2"
gunicorn = "^20.0.4"
toml = "^0.10.1"
requests = "^2.23.0"
wikipedia = "^1.4.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^3.8.3"
black = "^19.10b0"
isort = "^4.3.21"
mypy = "^0.780"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
